dist: trusty

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: Server
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/SoPra-Team-10/Server.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
  sonarcloud:
    organization: "sopra-team-10"
    token:
      secure: $SONAR_TOKEN

services:
  - docker

before_install:
  - docker build --no-cache -t server .

script:
- docker run server Tests/Tests --gtest_repeat=10 --gtest_shuffle --gtest_color=yes
  #- sonar-scanner
  
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocumentationAndDeploy.sh
- ./generateDocumentationAndDeploy.sh
  
notifications:
    slack: soprateam10:wlcgvL7tR63frGyGP4BCuqNj
