dist: trusty

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: Server
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/SoPra-Team-10/Server.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

services:
  - docker

before_install:
  - docker build --no-cache -t server .

script:
  - docker run -e SONAR_TOKEN=${SONAR_TOKEN} -e TRAVIS_BRANCH=${TRAVIS_BRANCH} server bash run-sonarqube.sh
  - docker run server build/Tests/Tests --gtest_repeat=10 --gtest_shuffle --gtest_color=yes

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

notifications:
  slack: soprateam10:${TRAVIS_TOKEN}